# Example configuration file for a job that runs every minute

# Connectors
connectors:
  source: 
    type: filesystem
    base_path: raw/minute-example
    partition: hourly
  destination: 
    type: filesystem
    base_path: ingested/minute-example
    partition: hourly

# Data source metadata
data_source:
  domain: minute-example
  name: minute_test
  source: 
    connector: source
    fqn_resource: test
    is_cdc: false
    primary_key: [id]
    timestamp_field: created_at
  destination:
    connector: destination
    ordering: [id asc]
  trigger:
    cron: "* * * * *"  # Run every minute
    random_offset: false
  validate:
    not_null: [id, value]
    unique: [id]
  fields:
    - label: id
      data_type: string
    - label: value
      data_type: string
    - label: created_at
      data_type: timestamp
